substitutions:
  _SERVICE_NAME: "dockbloxx-dev-staging"
  _REGION: "us-east1"
  _NEXT_PUBLIC_APP_URL: "https://REPLACE_ME_WITH_CUSTOM_DOMAIN_OR_FINAL_URL"
  _NEXT_PUBLIC_BACKEND_URL: "https://dockbloxx.mystagingwebsite.com"
  _NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: "pk_test_REPLACE_ME"

steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    secretEnv:
      - "WOOCOM_CONSUMER_KEY"
      - "WOOCOM_CONSUMER_SECRET"
      - "STRIPE_SECRET_KEY"
    args:
      - "-c"
      - |
        docker build \
          --build-arg WOOCOM_CONSUMER_KEY="$$WOOCOM_CONSUMER_KEY" \
          --build-arg WOOCOM_CONSUMER_SECRET="$$WOOCOM_CONSUMER_SECRET" \
          --build-arg STRIPE_SECRET_KEY="$$STRIPE_SECRET_KEY" \
          --build-arg NEXT_PUBLIC_APP_URL="${_NEXT_PUBLIC_APP_URL}" \
          --build-arg NEXT_PUBLIC_BACKEND_URL="${_NEXT_PUBLIC_BACKEND_URL}" \
          --build-arg NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY="${_NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}" \
          -t "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest" \
          .

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest"]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      [
        "run",
        "deploy",
        "${_SERVICE_NAME}",
        "--image",
        "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest",
        "--region",
        "${_REGION}",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--service-account",
        "stark-vertex-ai@$PROJECT_ID.iam.gserviceaccount.com",
        "--set-secrets",
        "WOOCOM_CONSUMER_KEY=woocom-consumer-key:latest,WOOCOM_CONSUMER_SECRET=woocom-consumer-secret:latest,STRIPE_SECRET_KEY=stripe-secret-key:latest",
        "--memory",
        "1Gi",
        "--max-instances",
        "1",
      ]

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/woocom-consumer-key/versions/latest
      env: "WOOCOM_CONSUMER_KEY"
    - versionName: projects/$PROJECT_ID/secrets/woocom-consumer-secret/versions/latest
      env: "WOOCOM_CONSUMER_SECRET"
    - versionName: projects/$PROJECT_ID/secrets/stripe-secret-key/versions/latest
      env: "STRIPE_SECRET_KEY"
